import vm from "node:vm";
import JSZip from "jszip";
import { JSDOM } from "jsdom";
import { describe, expect, it } from "vitest";
import { buildPackage } from "@/lib/generator/build";
import { zipBuffer } from "@/lib/generator/zip";
import { NpmName, SemVer, type Project } from "@/lib/model";
import { addNode, createFile } from "@/lib/scaffold";
import { getManifests, manifestClasses } from "@/lib/templates";
import { inputs, project } from "@/test/figmaProject";

const build = (p: Project = project("mobile-first")) => buildPackage(p, inputs(p.approach));
const fileOf = (files: { path: string; content: string }[], path: string) =>
  files.find((f) => f.path === path)?.content;

describe("buildPackage developer extras", () => {
  it("adds VARIABLES.md, the sample page and the style guide after the entry and README", async () => {
    const pkg = await build();
    expect(pkg.blocked).toBe(false);
    expect(pkg.files.slice(0, 8).map((f) => f.path)).toEqual([
      "acme-health.css",
      "README.md",
      "VARIABLES.md",
      "index.html",
      "style-guide/index.html",
      "style-guide/styleguide.css",
      "style-guide/styleguide.js",
      "style-guide/states.css",
    ]);
    expect(pkg.files.some((f) => f.path === "package.json")).toBe(false);
    expect(pkg.folders[0]).toBe("style-guide");
  });

  it("adds package.json when the npm option is on, and reserves the name", async () => {
    const p = {
      ...project("mobile-first"),
      npm: { enabled: true, name: "@acme/health-css", version: "2.1.0" },
    };
    const pkg = await build(p);
    const json = JSON.parse(fileOf(pkg.files, "package.json")!);
    expect(json).toEqual({
      name: "@acme/health-css",
      version: "2.1.0",
      description: "Acme Health CSS package generated by AuthorKit",
      private: true,
      style: "acme-health.css",
      exports: {
        ".": "./acme-health.css",
        "./tokens.css": "./css/tokens.css",
        "./css/*": "./css/*",
        "./package.json": "./package.json",
      },
      files: ["acme-health.css", "css/", "style-guide/", "README.md", "VARIABLES.md", "index.html"],
      sideEffects: ["*.css"],
      keywords: ["css", "design-tokens", "aem", "authorkit"],
    });
    expect(fileOf(pkg.files, "README.md")).toContain("## Installing as an npm package");
    expect(fileOf(pkg.files, "README.md")).toContain('@import "@acme/health-css";');

    const clash = {
      ...p,
      scaffold: addNode(p.scaffold, p.scaffold.id, createFile("package.json")),
    };
    const blocked = await build(clash);
    expect(blocked.blocked).toBe(true);
    expect(blocked.problems[0].message).toBe(
      '"package.json" is generated automatically at the package root',
    );
  });

  it("zips everything, including the style guide, byte-for-byte reproducibly", async () => {
    const [a, b] = await Promise.all([build().then(zipBuffer), build().then(zipBuffer)]);
    expect(a.equals(b)).toBe(true);
    const names = Object.keys((await JSZip.loadAsync(a)).files);
    expect(names).toContain("acme-health/style-guide/");
    expect(names).toContain("acme-health/style-guide/index.html");
    expect(names).toContain("acme-health/index.html");
    expect(names).toContain("acme-health/VARIABLES.md");
  });

  it("documents the extras in the README", async () => {
    const readme = fileOf((await build()).files, "README.md")!;
    expect(readme).toContain("## Style guide");
    expect(readme).toContain("Open `style-guide/index.html` in a browser.");
    expect(readme).toContain("├── VARIABLES.md  ← every CSS variable per file");
    expect(readme).toContain("├── style-guide/  ← developer style guide (folder)");
  });
});

describe("sample page", async () => {
  const pkg = await build();
  const html = fileOf(pkg.files, "index.html")!;
  const doc = new JSDOM(html).window.document;
  const known = new Set(Object.values(getManifests()).flatMap((m) => manifestClasses(m, "acme")));

  it("links only the entry stylesheet", () => {
    expect(
      [...doc.querySelectorAll("link[rel=stylesheet]")].map((l) => l.getAttribute("href")),
    ).toEqual(["acme-health.css"]);
  });

  it("uses only documented classes and shows every included component", () => {
    const used = new Set([...doc.querySelectorAll("[class]")].flatMap((el) => [...el.classList]));
    for (const c of used) expect(known, c).toContain(c);
    for (const block of [
      "acme-header",
      "acme-footer",
      "acme-btn",
      "acme-accordion",
      "acme-isi",
      "acme-isi-bar",
      "acme-modal",
    ]) {
      expect(used, block).toContain(block);
    }
  });

  it("starts with the modal closed and no missing images", () => {
    expect(doc.querySelector("dialog")!.hasAttribute("open")).toBe(false);
    for (const img of doc.querySelectorAll("img"))
      expect(img.getAttribute("src")).toMatch(/^data:image\/svg\+xml,/);
  });

  it("has a script that parses and uses the project prefix", () => {
    const script = doc.querySelector("script")!.textContent!;
    expect(() => new vm.Script(script)).not.toThrow();
    expect(script).toContain('var P = "acme";');
  });
});

describe("VARIABLES.md", async () => {
  const pkg = await build();
  const doc = fileOf(pkg.files, "VARIABLES.md")!;

  it("lists what each file defines and uses", () => {
    expect(doc).toContain("## `css/tokens.css`");
    expect(doc).toContain("| `--acme-font-size-h1` | `28px` | `(min-width: 1024px)`: `40px` |");
    expect(doc).toContain("## `css/components/footer.css`");
    expect(doc).toContain("- `--acme-color-footer-background` (from `css/tokens.css`)");
  });

  it("mentions every custom property in the package", () => {
    const css = pkg.files
      .filter((f) => f.path.endsWith(".css") && !f.path.startsWith("style-guide/"))
      .map((f) => f.content)
      .join("\n");
    const declared = new Set([...css.matchAll(/(--acme-[a-z0-9-]+)\s*:/g)].map((m) => m[1]));
    for (const name of declared) expect(doc, name).toContain(`\`${name}\``);
  });
});

describe("npm options validation", () => {
  it.each(["acme-health-css", "@acme/health-css", "a.b_c~d", "x"])("accepts name %s", (name) => {
    expect(NpmName.safeParse(name).success).toBe(true);
  });
  it.each(["Acme", "has space", "@scope", "../x", "", "a".repeat(215)])(
    "rejects name %j",
    (name) => {
      expect(NpmName.safeParse(name).success).toBe(false);
    },
  );
  it.each(["1.0.0", "0.1.12", "2.0.0-beta.1"])("accepts version %s", (v) => {
    expect(SemVer.safeParse(v).success).toBe(true);
  });
  it.each(["1.0", "v1.0.0", "01.0.0", "1.0.0 "])("rejects version %j", (v) => {
    expect(SemVer.safeParse(v).success).toBe(false);
  });
});
