import type { GeneratedFile } from "@/lib/generator/types";
import { README_NAME, SAMPLE_PAGE, STYLE_GUIDE_DIR, VARIABLES_DOC } from "@/lib/generator/naming";
import type { NpmOptions, Project } from "@/lib/model";

/**
 * package.json for installing the CSS as an npm dependency. Private by
 * default so it cannot be published by accident.
 */
export function renderPackageJson(
  project: Pick<Project, "brandName" | "scaffold">,
  npm: NpmOptions,
  entryName: string,
  files: GeneratedFile[],
): string {
  const folders = project.scaffold.children.filter((c) => c.type === "folder").map((c) => c.name);
  const rootFiles = project.scaffold.children.filter((c) => c.type === "file").map((c) => c.name);
  const tokens = files.find((f) => f.templateId === "tokens")?.path;

  const exports: Record<string, string> = { ".": `./${entryName}` };
  if (tokens) exports["./tokens.css"] = `./${tokens}`;
  for (const folder of folders) exports[`./${folder}/*`] = `./${folder}/*`;
  exports["./package.json"] = "./package.json";

  const pkg = {
    name: npm.name,
    version: npm.version,
    description: `${project.brandName} CSS package generated by AuthorKit`,
    private: true,
    style: entryName,
    exports,
    files: [
      entryName,
      ...rootFiles,
      ...folders.map((f) => `${f}/`),
      `${STYLE_GUIDE_DIR}/`,
      README_NAME,
      VARIABLES_DOC,
      SAMPLE_PAGE,
    ],
    sideEffects: ["*.css"],
    keywords: ["css", "design-tokens", "aem", "authorkit"],
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}
