import { CSS_TEMPLATE_LABELS, type CssTemplateId } from "@/lib/model";
import { commentSafe } from "@/lib/templates/context";

/** Cascade order: tokens first, then base styles, then components. */
export const ENTRY_ORDER: readonly CssTemplateId[] = [
  "tokens",
  "global",
  "cta",
  "accordion",
  "header",
  "footer",
  "isi",
  "modals",
];

export type CssFileRef = { path: string; templateId: CssTemplateId | null };

/** Templated files in ENTRY_ORDER (tree order within a template), then untemplated CSS in tree order. */
export function orderForImport(files: readonly CssFileRef[]): CssFileRef[] {
  const rank = (f: CssFileRef) =>
    f.templateId ? ENTRY_ORDER.indexOf(f.templateId) : ENTRY_ORDER.length;
  return files
    .map((f, i) => ({ f, i }))
    .sort((a, b) => rank(a.f) - rank(b.f) || a.i - b.i)
    .map(({ f }) => f);
}

export function importLabel(file: CssFileRef): string {
  return file.templateId ? CSS_TEMPLATE_LABELS[file.templateId] : "No template (your own styles)";
}

export function renderEntry(
  brandName: string,
  entryName: string,
  files: readonly CssFileRef[],
): string {
  const ordered = orderForImport(files);
  const lines = [
    "/*!",
    ` * ${commentSafe(brandName)} · ${entryName}`,
    " * Package entry. Generated by AuthorKit; regenerate instead of editing by hand.",
    " *",
    " * Link this one file, or load the files below yourself in the same order.",
    " */",
    "",
    ...ordered.map((f) => `@import url("${f.path}");`),
  ];
  if (ordered.length === 0) lines.push("/* The scaffold has no CSS files yet. */");
  return lines.join("\n") + "\n";
}
