import { describeRange, mediaQueries } from "@/lib/breakpoints";
import { CSS_TEMPLATE_LABELS, type Project } from "@/lib/model";
import { renderTreeText } from "@/lib/scaffold/render";
import { getManifests, manifestClasses, type GenerationReport } from "@/lib/templates";
import { classMapFor, mapManifests } from "@/lib/selectors/map";
import { importLabel, orderForImport, type CssFileRef } from "./entry";
import { README_NAME, generatedRootEntries } from "./naming";

/** One line, no markdown control characters that could break the layout. */
const inline = (text: string) => text.replace(/[\r\n]+/g, " ").replace(/[`|]/g, "");

/** "Design sources": how much came from Figma and which values are still template defaults. */
function designSources(
  report: GenerationReport,
  prefix: string,
  cssFiles: readonly CssFileRef[],
): string[] {
  // Only count values for templates this package actually contains.
  const files = new Set(cssFiles.flatMap((f) => (f.templateId ? [`${f.templateId}.css`] : [])));
  const rows = report.rows.filter((r) => files.has(r.file));
  const fromFigma = rows.filter((r) => r.source !== "default").length;
  const defaults = rows.filter((r) => r.source === "default");
  if (fromFigma === 0 && report.extras.length === 0) {
    return [
      "## Design sources",
      "",
      "No values from Figma yet: every value uses AuthorKit's defaults. Connect the project to Figma in AuthorKit and regenerate.",
      "",
    ];
  }
  const lines = [
    "## Design sources",
    "",
    `- **From Figma:** ${fromFigma} value${fromFigma === 1 ? "" : "s"} (design tokens and per-breakpoint component values)`,
    `- **AuthorKit defaults:** ${defaults.length} value${defaults.length === 1 ? "" : "s"} not yet defined in the design`,
  ];
  if (report.extras.length) {
    lines.push(
      `- **Extra values from Figma:** ${report.extras.map((n) => `\`--${prefix}-${n}\``).join(", ")} (in \`tokens.css\`, for your own CSS)`,
    );
  }
  if (defaults.length) {
    lines.push("", "Values still using defaults:", "");
    const byFile = new Map<string, string[]>();
    for (const r of defaults)
      byFile.set(r.file, [...(byFile.get(r.file) ?? []), `\`--${prefix}-${r.name}\``]);
    for (const [file, names] of byFile) lines.push(`- \`${file}\`: ${names.join(", ")}`);
  }
  lines.push("");
  return lines;
}

export function renderReadme(
  project: Project,
  entryName: string,
  cssFiles: readonly CssFileRef[],
  report?: GenerationReport,
): string {
  const p = project.prefix;
  const brand = inline(project.brandName);
  const ordered = orderForImport(cssFiles);
  const queries = mediaQueries(project.breakpoints.breakpoints, project.approach);
  const byId = new Map(project.breakpoints.breakpoints.map((b) => [b.id, b]));
  const smallestFirst = project.approach === "mobile-first";
  const usedTemplates = new Set(cssFiles.flatMap((f) => (f.templateId ? [f.templateId] : [])));
  const manifests = Object.values(mapManifests(getManifests(), classMapFor(project))).filter(
    (m) => usedTemplates.has(m.id) && m.id !== "tokens",
  );

  const tree = renderTreeText(
    project.scaffold,
    generatedRootEntries(project).map((e) => ({
      name: e.name,
      note: e.name === README_NAME ? "this file" : e.note,
    })),
  );
  const npm = project.npm?.enabled ? project.npm : undefined;

  const sections = [
    `# ${brand} CSS package`,
    "",
    `Generated by AuthorKit from the “${inline(project.name)}” project.`,
    "",
    `- **Class prefix:** \`${p}\``,
    `- **Responsive approach:** ${project.approach}`,
    `- **Files:** ${cssFiles.length} stylesheet${cssFiles.length === 1 ? "" : "s"} plus \`${entryName}\``,
    "",
    "> Do not edit these files by hand. Change the project in AuthorKit and regenerate,",
    "> so the CSS, the style guide and this README stay in sync.",
    "",
    "## Quick start",
    "",
    "```html",
    `<link rel="stylesheet" href="${entryName}">`,
    "```",
    "",
    `\`${entryName}\` imports every stylesheet in the right order. To load the files yourself`,
    "(for example in an AEM clientlib), keep this order:",
    "",
    ...(ordered.length
      ? ordered.map((f, i) => `${i + 1}. \`${f.path}\`: ${importLabel(f)}`)
      : ["_No stylesheets in this package yet._"]),
    "",
    "## Style guide",
    "",
    "Open `style-guide/index.html` in a browser. It works offline, straight from the file system:",
    "live examples of every component, the classes to apply in your AEM components, copyable HTML",
    "and HTL, states, accessibility notes, and every design token. Use *Inspect classes* to click",
    "an element in an example and see its classes.",
    "",
    "## Sample page",
    "",
    "`index.html` is a one-page demo of the components using only the stylesheet above. Its small",
    "script shows how to wire the documented JavaScript hooks (menu, accordion, safety bar and modals).",
    "",
    "## Variables reference",
    "",
    "`VARIABLES.md` lists every CSS variable file by file: what each file defines, with per-breakpoint",
    "values, and which variables it uses.",
    "",
    ...(npm
      ? [
          "## Installing as an npm package",
          "",
          `This folder is an npm package named \`${npm.name}\` (version ${npm.version}). It is marked`,
          'private so it cannot be published by accident; remove `"private": true` before publishing it',
          "to your registry. To use it from a local folder:",
          "",
          "```bash",
          `npm install ./${project.scaffold.name}`,
          "```",
          "",
          "```css",
          `@import "${npm.name}";`,
          `@import "${npm.name}/tokens.css";`,
          "```",
          "",
        ]
      : []),
    "## Folder structure",
    "",
    "```",
    tree,
    "```",
    "",
    "## Breakpoints",
    "",
    "| Name | Screen width | Media query |",
    "| --- | --- | --- |",
    ...queries.map(
      (q) =>
        `| ${q.name} | ${describeRange(byId.get(q.breakpointId)!)} | ${
          q.condition ? `\`@media ${q.condition}\`` : "base styles (no media query)"
        } |`,
    ),
    "",
    smallestFirst
      ? "Mobile-first: base styles target the smallest screen. Each `min-width` query adds changes for larger screens."
      : "Desktop-first: base styles target the largest screen. Each `max-width` query adds changes for smaller screens.",
    "Look for `/* @authorkit-responsive … */` comments in each file to find the overrides for a breakpoint.",
    "",
    "## Naming",
    "",
    `Every class uses BEM with the \`${p}-\` prefix, so these styles cannot collide with other CSS on the page:`,
    "",
    `- Block: \`.${p}-btn\``,
    `- Element: \`.${p}-btn__icon\``,
    `- Modifier: \`.${p}-btn--primary\``,
    `- Custom property (token): \`--${p}-color-primary\``,
    "",
    ...(usedTemplates.has("global")
      ? [
          "`global.css` also styles plain HTML elements (`h1`–`h6`, `p`, `a`, `sup`, `sub`, lists and images),",
          "so rich text from authors is styled without extra classes.",
          "",
        ]
      : []),
    "## Customising",
    "",
    "All design values are CSS custom properties. Override a token after loading the package:",
    "",
    "```css",
    ":root {",
    `  --${p}-color-primary: #0b4f8a;`,
    "}",
    "```",
    "",
  ];

  if (report) sections.push(...designSources(report, p, cssFiles));

  if (manifests.length) {
    sections.push("## Components", "", "| File | Component | Classes |", "| --- | --- | --- |");
    for (const m of manifests) {
      const files = cssFiles
        .filter((f) => f.templateId === m.id)
        .map((f) => `\`${f.path}\``)
        .join(", ");
      const classes = manifestClasses(m, p)
        .map((c) => `\`.${c}\``)
        .join(" ");
      sections.push(`| ${files} | ${CSS_TEMPLATE_LABELS[m.id]} | ${classes} |`);
    }
    sections.push("");
  }

  return sections.join("\n");
}
